sampling_run_id: "20240109-0001" # "20220602-0001" #"20240109-0001"
sample_file:
  data_dir: "data"
  sampling_data_path: "data/{sampling_run_id}/Sampling.csv"

country_code:
  - "sg"
  - "th"
  - "tw"
  - "id"
  - "my"
  - "sa"
  # - "gb"
  # - "us"
  # - "fr"
  # - "de"
  # - "it"
  # - "es"
  # - "nl"
  # - "be"
  # - "ca"
  # - "pl"


output_file:
  output_dir: "data/{sampling_run_id}/output/{country_code}"
  output_file_name: "samples_normalized.csv"

columns_to_llm:
  - country
  - sample_id
  - searched_query
  - lat
  - lon
  - searched_query_unidecode

output_json_keys:
  - country
  - sample_id
  - searched_query
  - normalized_address
  - normalized_address_unidecode

azure:
  api_version: 2024-02-15-preview
  max_tokens: 300
  max_tokens_few_shot: 1000
  max_tokens_batch: 500
  model: gpt-4o-mini
  temperature: 0.1
  token_limit: 15000

batch_size: 50